# Generated by Django 3.1.14 on 2025-05-16 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[['Available', 'available'], ['Finished', 'finished']], default='available', max_length=50)),
                ('finished_on', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rims', to='main.item')),
            ],
        ),
        migrations.CreateModel(
            name='Print',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnty', models.IntegerField(blank=True, null=True)),
                ('amount', models.BigIntegerField()),
                ('rim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prints', to='main.rim')),
            ],
        ),
    ]
