# Generated by Django 4.2.13 on 2025-05-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('product', 'Product'), ('service', 'Service')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
